Web workload identity
kedacore/sample-dotnet-worker-servicebus-queue pull request #62
Opened 2024-06-05 11:11 UTC by Richard87

2024-06-05 20:30 UTC, tomkerkhove requested changes

2024-06-05 20:30 UTC, tomkerkhove commented on deploy/pod-identity/deploy-app-with-pod-identity.yaml
> +        - name: OrderQueueOptions__AuthMode
Let's revert all of these renames and stick with current names

2024-06-05 20:30 UTC, tomkerkhove commented on src/Keda.Samples.Dotnet.Contracts/AddServiceBusClientExtension.cs
> +public class OrderQueueOptions
Let's align with the current way of working and create a file per class please

2024-06-05 20:30 UTC, tomkerkhove commented on src/Keda.Samples.Dotnet.Contracts/ApiTypes.cs
> +public record QueueStatus(long MessageCount);
Let's align with the current way of working and create a file per class please

2024-06-06 07:46 UTC, Richard87 commented on deploy/pod-identity/deploy-app-with-pod-identity.yaml
> +        - name: OrderQueueOptions__AuthMode
I would prefer to, but I don't know how when using DotNets option pattern., do you have any advice?

I could revert the configuration integration and just parse it myself in the options class, if that is preferable?

2024-06-06 08:12 UTC, Richard87 commented on src/Keda.Samples.Dotnet.Contracts/AddServiceBusClientExtension.cs
> +public class OrderQueueOptions
Fixed :)

2024-06-06 08:12 UTC, Richard87 commented on src/Keda.Samples.Dotnet.Contracts/ApiTypes.cs
> +public record QueueStatus(long MessageCount);
Fixed :)

2024-06-07 10:05 UTC, tomkerkhove commented on deploy/pod-identity/deploy-app-with-pod-identity.yaml
> +        - name: OrderQueueOptions__AuthMode
Let's revert it for now and keep it simple

2024-06-08 20:24 UTC, Richard87 commented on deploy/pod-identity/deploy-app-with-pod-identity.yaml
> +        - name: OrderQueueOptions__AuthMode
Can I suggest an upgrade? 

In the fork we have removed all auth options, and only retained AzureDefaultCredentials... What do you think about the same here, but also only checking if `KEDA_SERVICEBUS_CONNECTION_STRING` is used, and if so, only using that?

2024-06-08 20:25 UTC, Richard87 commented on deploy/pod-identity/deploy-app-with-pod-identity.yaml
> +        - name: OrderQueueOptions__AuthMode
btw, that was my last question, if you still want to retain the original features, I'll get right on it :)

2025-11-24 08:05 UTC, closed without merging